package it.codingjam.lifecyclebinder;

public enum LifeCycleEvent {
    CREATE, START, RESUME, PAUSE, STOP, DESTROY, SAVE_INSTANCE_STATE, ACTIVITY_RESULT, HAS_OPTION_MENU, CREATE_OPTION_MENU, OPTION_ITEM_SELECTED, VIEW_CREATED, DESTROY_VIEW;
}
